node {
    // Declare environment variables
    def IMAGE_NAME = "vikiardian/react-app"
    def CI = 'true'

    try {
        // Checkout SCM
        stage('Checkout SCM') {
            checkout scm
        }

        // Build Docker Image
        stage('Build') {
            script {
                docker.build("${IMAGE_NAME}:${env.BUILD_ID}")
            }
        }

        // Run Tests
        stage('Test') {
            script {
                def app = docker.image("${IMAGE_NAME}:${BUILD_ID}")
                app.inside {
                    sh 'npm install'
                    sh 'npm test'
                }
                echo 'Test successful!'
            }
        }

        // Push Docker Image
        stage('Push') {
            script {
                docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credential') {
                    docker.image("${IMAGE_NAME}:${env.BUILD_ID}").push()
                }
            }
        }

        // Trigger Another Job (Manifest Update)
        stage('Trigger manifest') {
            script {
                echo "Start another job"
                build job: 'updatemanifest', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
            }
        }

    } catch (Exception e) {
        currentBuild.result = 'FAILURE'
        throw e
    }
}
