pipeline {
    agent any

    environment {
        CI = 'true'
        IMAGE_NAME = "vikiardian/react-app"
        BUILDTAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:${env.BUILD_NUMBER}")
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    def app = docker.image("${IMAGE_NAME}:${env.BUILD_NUMBER}")
                    app.inside {
                        sh 'npm install'
                        sh 'npm test'
                    }
                    echo 'Test successful!'
                }
            }
        }

        stage('Push') {
            steps {
                script {
                    // Push Docker image ke registry Docker Hub
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credential') {
                        docker.image("${IMAGE_NAME}:${env.BUILD_NUMBER}").push()
                    }
                }
            }
        }

        stage('Trigger manifest update') {
            steps {
                script {
                    build job: 'updatemanifest',
                          propagate: false,
                          parameters: [
                            [$class: 'StringParameterValue', name: 'BUILDTAG', value: "${BUILDTAG}")
                          ]
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished"
        }

        success {
            echo "Pipeline finished successfully"
        }

        failure {
            echo "Pipeline failed"
        }
    }
}
