
pipeline {
    agent any

    environment {
        CI = 'true'
        IMAGE_NAME = "vikiardian/react-app"
        DOCKER_TAG = "${BUILD_NUMBER}"
        K8S_MANIFEST_JOB = 'updatemanifest'
    }
    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:${DOCKER_TAG}")
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    def app = docker.image("${IMAGE_NAME}:${DOCKER_TAG}")
                    app.inside {
                        sh 'npm install'
                        sh 'npm test'
                    }
                    echo 'Test successful!'
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credential') {
                        docker.image("${IMAGE_NAME}:${env.DOCKER_TAG}").push()
                    }
                }
            }
        }
        stage('Update Kubernetes Deployment Manifest') {
            steps {
                script {
                    echo "Triggering job to update Kubernetes deployment manifest..."
                    build job: K8S_MANIFEST_JOB, parameters: [
                        string(name: 'DOCKER_IMAGE', value: "${IMAGE_NAME}:${DOCKER_TAG}")
                    ]
                }
            }
        }
    }
}
